debug = false

logLevel = "ERROR"

defaultEntryPoints = ["https","http"]

[entryPoints]
  [entryPoints.dashboard]
    address = ":8080"
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]

[api]
entrypoint="dashboard"

[retry]

[acme]
email = "your-email-here"
storage = "acme.json"
entryPoint = "https"
onHostRule = true
  [acme.httpChallenge]
    entryPoint = "http"

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "your-domain-here"
watch = true
exposedByDefault = false
network = "hms-docker_web"
